spring.application.name=job-application-tracker
server.port=8080
spring.mongodb.host=localhost
spring.mongodb.port=27017
spring.mongodb.database=job_tracker_db
spring.data.mongodb.uri=${MONGO_URI}


spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


jwt.secret=${JWT_SECRET}
#15 minutes
jwt.access-token-expiration-ms=900000
# 7 days
jwt.refresh-token-expiration-ms=604800000
cookie.secure=false

# Debug Spring Security - remove after debugging
logging.level.org.springframework.security=DEBUG
